### ISSUE TITLE
ERROR: Value cannot be null. (Parameter 'collection') - HTML chat download

### ISSUE THREAD

**Issue by MrDummyNL** [lay295/TwitchDownloader#630] opened 2023-03-23 10:55 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I have no errors in version earlier 1.52.1 with HTML chat download, but new version 1.52.2 it throw immediately error because something is null.

So i cannot download HTML version of chat. Please take a look what is wrong there in last version.
Happens in manual and batched download.

TXT and JSON worked, but only HTML is broken right now, even you made some improvements since earlier version.
Even turning off other emotes will not help it.

**Comment by SlyCooperReloadCoded** [comment] 2023-03-23 20:46
Okay I was waiting to see if this wasn't just an issue I was having.  I was able to fix this by downgrading to the previous release, at least until it's fixed in the latest release.

**Comment by ScrubN** [comment] 2023-03-23 20:56
I was able to confirm this is a duplicate of #622 and it has been fixed for next release. You can either use an older version or temporarily use a workflow build from after it has been patched: https://github.com/lay295/TwitchDownloader/actions/runs/4485587295

**Closed by ScrubN** 2023-03-23 20:56 UTC
Labels: bug
