### ISSUE TITLE
404 Error on Chat Render and Clip not Pasting properly 

### ISSUE THREAD

**Issue by NeroP2020** [lay295/TwitchDownloader#148] opened 2021-02-18 18:53 UTC
I've been getting an error when trying to render the chat. [It looks like this.](https://gyazo.com/600912b4b94eeed8b7c6c53dfdc45632) VOD download, clip download and chat download are all working fine.

Edit: Clip Downloads are not working as well. 
Error: ERROR: _System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderCore.TwitchHelper.<GetClipInfo>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchDownloaderWPF.PageClipDownload.<btnGetInfo_Click>d__3.MoveNext() in C:\Users\Lewis Pardo\Document1gBz3WERkVCCnx9jQhUShgvSC69WVHhLeR.xaml.cs:line 56_

Edit 2: Clip downloads are actually working, but not properly. When I copy and past a clip link into the Link/ID section it's not properly pasting the link. For example this clip: https://clips.twitch.tv/SteamyPricklyBarracudaItsBoshyTime-CsGHyld1L3LehqIc (I manually typed this out) turns into: https://clips.twitch.tv/Sa3upprKvUsQGKB12infMQL8bNHruqWjnm-CsGHyld1L3LehqIc, which isn't a real clip when pasted into chrome. 

Edit 3: Upon further research, The clip is not pasting properly into chrome or any other program. It's not just an issue with this program. I don't know if this is just a me problem or if this is just happening to anyone else and it's just a twitch issue.

**Comment by lay295** [comment] 2021-02-18 20:38
Well glad you figured out the clips thing, because I've been able to download clips just fine and couldn't really figure out what was wrong. Others were reporting the issue.

But it seems like Twitch added a new predictions badge besides the Blue and Pink ones, a grey one, without an image currently... the program currently assumes that all badges that are returned by the API actually exist so it's messing up. Maybe Twitch will upload an image for it soon? Either way I will update the program so if a badge doesn't exist it'll still complete. 

![image](https://user-images.githubusercontent.com/1060681/108418514-5d3fe600-71ff-11eb-988b-9c588180ce0a.png)

**Comment by lay295** [comment] 2021-02-18 22:28
Should be fixed in 1.39.4, I don't really know what to do about the clips thing since I can't reproduce it on my end.

**Comment by NeroP2020** [comment] 2021-02-18 22:37
The program is crashing for me when rendering a JSON.

**Comment by CookieRL** [comment] 2021-02-18 22:42
The program is also crashing for me when rendering the clip

**Comment by lay295** [comment] 2021-02-19 00:24
Can you upload a JSON please? I can't reproduce it, and another computer I can't reproduce it.'

At what point does it crash? Immediately after you hit render chat?

**Comment by NeroP2020** [comment] 2021-02-19 00:34
It crashes during the "rendering video" stage. The percent it crashes at is random every time.

**Comment by lay295** [comment] 2021-02-19 00:42
I assume same as #57, and my new Github Actions build script for some reason breaks my optimization fix >:( I don't have time to look into this right now so I built it myself and updated the release. Redownload and give it a try.

**Comment by CookieRL** [comment] 2021-02-19 02:37
Working now thanks!

**Closed** 2021-02-19 04:44 UTC
