### ISSUE TITLE
ERROR: Attempted to divide by zero.

### ISSUE THREAD

**Issue by minecraftismylife1** [lay295/TwitchDownloader#1135] opened 2024-07-07 10:10 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When i try to render with low fps chat i get ERROR: Attempted to divide by zero.
For example it renders properly with 60 fps, but throws this error when i try to render in 5 fps(ofc i dont need just a text rendered in 60 fps - it's a waste of space on my ssd). I came up with 10 as the lowest value without error,

**Comment by ScrubN** [comment] 2024-07-07 16:33
Unfortunately I can't reproduce the error, nor can I find where a divide by zero would occur when fps is 5. If you could enable "verbose errors" in the settings and send a screenshot of the error popup, it would help tremendously.

**Comment by minecraftismylife1** [comment] 2024-07-07 16:52
![123123](https://github.com/lay295/TwitchDownloader/assets/64714846/0c63676c-a012-4921-86d6-acd6a1fa8b29)

**Comment by ScrubN** [comment] 2024-07-07 21:01
I have no clue how this issue wasn't reported earlier with how long that code has been untouched, however it will be fixed in the next release. Until then, you can render at low framerates by simply setting the update rate to `0`.

**Closed** 2024-07-07 21:02 UTC
Labels: bug
