### ISSUE TITLE
[BUG] Issue when using CLI to download a stream on ubuntu

### ISSUE THREAD

**Issue by Stinosko** [lay295/TwitchDownloader#93] opened 2020-11-13 14:07 UTC
I get following error when downloading a stream using the CLI with Ubuntu 20.4.1 LTS server:

> Unhandled exception. System.AggregateException: One or more errors occurred. (No such file or directory)
>  ---> System.ComponentModel.Win32Exception (2): No such file or directory
>    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at TwitchDownloaderCore.VideoDownloader.<>c__DisplayClass2_1.<DownloadAsync>b__2()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location where exception was thrown ---
>    at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at TwitchDownloaderCLI.Program.DownloadVideo(Options inputOptions)
>    at TwitchDownloaderCLI.Program.Main(String[] args)
> Aborted

Command used is: `./TwitchDownloaderCLI -m VideoDownload --id 800525570 -o video.mp4`
It happens right after `[STATUS] - Finalizing MP4 (3/3)`

**Comment by goldbattle** [comment] 2020-11-17 21:03
Do you have permissions to create the output folder?

**Comment by Stinosko** [comment] 2020-11-17 21:09
Yes as the rendering command does worked correctly and output the rendered file in the same directory with the same permissions...

**Comment by lay295** [comment] 2020-11-17 21:20
Oh sorry forgot to get around to replying was a little busy.

I assume it's not correctly finding the ffmpeg executable for some reason. Is ffmpeg in the same directory as the CLI or is it part of the linux PATH?

**Comment by Stinosko** [comment] 2020-11-17 21:23
It's inside my linux PATH 🙂

**Comment by Stinosko** [comment] 2020-11-17 23:06
Adding `--ffmpeg-path /bin/ffmpeg` fixed it, so not sure it's a bug but maybe possible feature to check if ffmpeg is in the $PATH instead of only looking at the folder? As installing ffmpeg on ubuntu is just as simple as `apt install ffmpeg`and it's added to the path automatically 🙂

**Comment by Stinosko** [comment] 2020-11-18 12:31
I will close the issue

**Comment by lay295** [comment] 2020-11-18 21:27
It's supposed to take the executable from the path, and since it works for the chat render it's a bug. I'll try and reproduce it and fix it later when I have time

**Comment by lay295** [comment] 2020-11-20 00:23
Should be fixed in 1.38

**Closed by lay295** 2020-11-20 00:23 UTC
