### ISSUE TITLE
Audio out of sync when cutting VOD

### ISSUE THREAD

**Issue by trevormbell** [lay295/TwitchDownloader#556] opened 2023-02-23 15:01 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When downloading a full VOD everything works perfectly, but if I try to only download a portion of the VOD the audio is out of sync with the video when playing it back. I have tried on multiple VODs and it always happens.

**Comment by ScrubN** [comment] 2023-02-23 23:28
I compared the gunshots of a VOD in the Twitch player and a cropped download in Sony Vegas 17.0 at 0.25x and found no desync.

**Comment by trevormbell** [comment] 2023-02-24 00:28
the desync I'm getting is close to a second or more. I did more testing and found it's only out of sync when playing back in VLC, windows player works fine. VLC will still play the uncut VODs properly though. maybe it's a problem on my end but I can't see what would cause such a weird edge case.

**Comment by lay295** [comment] 2023-02-24 00:46
It's almost certainly a duplicate of #531 #67

Again could either re-encode 1st part (which will inevitability have _some_ loss in quality

Or could [parse out the keyframes](https://superuser.com/questions/554620/how-to-get-time-stamp-of-closest-keyframe-before-a-given-timestamp-with-ffmpeg) and cut on the nearest one. Would still not be totally accurate cut but no desync. Would have to bundle ffprobe too which would suck though.

**Comment by indeboss** [comment] 2023-02-26 11:29
Had the same issue with some media players having a desynchronized audio, as well as some video editors: Davinci Resolve worked fine but with everything else I'd have to manually adjust the audio. Doesn't happen all the time though, don't know why. A huge bummer since downloading portions of a vod is all I need the tool for, and most of the times a download either fails for an unknown reason or results in a desynchronized audio.

**Comment by ScrubN** [comment] 2023-02-26 20:22
> Had the same issue with some media players having a desynchronized audio, as well as some video editors: Davinci Resolve worked fine but with everything else I'd have to manually adjust the audio. Doesn't happen all the time though, don't know why.

The only application I have found that has any of the desync/freezing issues is VLC. Other media players/editors such as MPV, Sony Vegas, Blender all correctly played the video file.

> A huge bummer since downloading portions of a vod is all I need the tool for, and most of the times a download either fails for an unknown reason or results in a desynchronized audio.

You can re-encode the downloads with Handbrake, Ffmpeg, or XMedia Recode and it will fix the odd playback issues.

**Comment by PeterPedro** [comment] 2023-04-04 06:34
I also have this issue, the problem seems to be random because some videos are fine, what I do is download  the video again from a few seconds before or after until the file doesn't have the sync issue. I blame ffmpeg because if I download segments directly with it I also get the issue.

One thing I noticed is that the start of the video seems to have an issue (the first couple seconds have no audio data) and VLC just plays the video and audio assuming they are synced from the beginning (this causes the problem with VLC).

Other players wait for the audio and video to sync, so the first couple seconds of the video have no audio and then when the audio finally starts then all is perfectly synced.

This issue with the beginning of the videos also causes other random issues in other players.

**Comment by nazsol** [comment] 2023-04-15 10:47
Have same issue, only happens with some cut VOD's and only with VLC player, works fine with Windows Media Player, i guess i could switch players when i have the issue but still annoying, come to think of it might just be a issue with VLC itself.

**Comment by indeboss** [comment] 2023-04-17 22:17
I think QuickTime shows the 2002 error when trying to open a downloaded vod because of this issue as well

**Closed** 2024-06-27 02:58 UTC
Labels: bug
