### ISSUE TITLE
CLI version stage 4/4 percentage miscalculation

### ISSUE THREAD

**Issue by Kamizol** [lay295/TwitchDownloader#716] opened 2023-05-22 18:33 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

When downloading a VOD using the CLI tool, the percentage on the stage 4/4 goes from 0 to 2147483647% and doesn't change until completion :

[STATUS] - Finalizing Video 2147483647% [4/4]

**Comment by ScrubN** [comment] 2023-05-22 19:54
Sounds like a duplicate of #711. Can you verify if this [workflow build](https://github.com/lay295/TwitchDownloader/actions/runs/5040638175) has fixed the issue?

**Comment by Kamizol** [comment] 2023-05-23 05:43
I don't think it's the same as it went from 0 to 2147483647 directly (no in between) and then nothing until completion (where it showed 100% at last)

I'll test the workflow build and get back to you asap

**Comment by Felanbird** [comment] 2023-07-17 00:56
I ran into this issue but with max int being in the negative, but as expected it downloaded correctly and _just_ skipped to 100% when it was done. 
This is on the latest current release, which would include the workflow mentioned above.
![image](https://github.com/lay295/TwitchDownloader/assets/41973452/f557ed15-1e9f-48e0-a43f-8e9eb1838a51)

**Comment by ScrubN** [comment] 2023-07-17 01:40
Hmmmm. This is a bit of a weird issue because all we're doing is:
```cs
var percent = (int)(encodingTime.TotalSeconds / videoLength * 100);
```
where `videoLength` is the length of the video used to construct the ffmpeg command and `encodingTime` is parsed from the ffmpeg output, `frame=73723 fps=8177 q=-1.0 size=  910848kB time=00:20:29.52 bitrate=6068.7kbits/s speed= 136x`. Both of these are 64-bit float values, however `videoLength` can only be whole numbers due to user input restrictions.

Even in a worst case of ffmpeg incorrectly printing `time=99:99:99.99` for a 1 second download, that would only report the percent as `36243909`. Note, any output from ffmpeg that does not fit `time=##:##:##.##` is discarded.

Because of this I might just opt to not reporting a percentage when it is out of range, unless you have any other ideas.

**Comment by Felanbird** [comment] 2023-07-17 07:43
> Even in a worst case of ffmpeg incorrectly printing time=99:99:99.99 for a 1 second download, that would only report the percent as 36243909. Note, any output from ffmpeg that does not fit time=##:##:##.## is discarded.

I read this and thought that I may have user-error'd you, as I didn't check what ffmpeg version I was using, and it happened to be one from 2020, but after an update and PC restart I'm still able to replicate this issue.

While I'm not downloading 1s long vods of course, I did make sure to re-test with vod(s) at least closely as long as the original. 
The original download was `08:32:46` and the re-tests were `07:26:27`, `07:20:50`, and `08:08:46` respectively.

I just did lazy downloading directly from the downloads folder, and I named the output file the same as the ID. `TwitchDownloaderCLI.exe videodownload --id 1870436097 -o 1870436097.mp4`

But other than some stupid bug that I accidentally found, no unfortunately I don't have any ideas for this problem, I don't actively download VODs I just wanted to save one that was going to get axed soon™️.

**Comment by ScrubN** [comment] 2023-07-18 04:46
> I read this and thought that I may have user-error'd you, as I didn't check what ffmpeg version I was using, and it happened to be one from 2020, but after an update and PC restart I'm still able to replicate this issue.

The ffmpeg installed on my system is also a compilation from 2020, so I'm not really sure.

> But other than some stupid bug that I accidentally found, no unfortunately I don't have any ideas for this problem

Just in case I added a `Math.Round` before the `int` cast, though I've never heard of casting number types resulting in an bug like this without also throwing an overflow exception.

**Closed** 2023-07-23 06:00 UTC
Labels: bug

**Comment by superbonaci** [comment] 2024-03-12 18:28
Modified code to get the error:
```
// Apparently it is possible for the percent to not be within the range of 0-100. lay295#716
            if (percent is < 0 or > 100)
            {
                progress.Report(new ProgressReport(ReportType.SameLineStatus, $"Finalizing Video... [5/{totalProgressSteps}]"));
                progress.Report(new ProgressReport(0));
                Console.WriteLine($"Percent out of range: {percent}%");
            }
            else
            {
                progress.Report(new ProgressReport(ReportType.SameLineStatus, $"Finalizing Video {percent}% [5/{totalProgressSteps}]"));
                progress.Report(new ProgressReport(percent));
            }
```
Log:
```
$ TwitchDownloaderCLI videodownload -u '2075185896' --temp-path  './TMP/' -o output.mp4
TwitchDownloaderCLI 1.54.1 Copyright (c) lay295 and contributors
[STATUS] - Fetching Video Info [1/5]
[STATUS] - Downloading 100% [2/5]
[STATUS] - Verifying Parts 100% [3/5]
[STATUS] - Combining Parts 100% [4/5]
[STATUS] - Finalizing Video 0% [5/5]Percent out of range: -2147483648%
[STATUS] - Finalizing Video... [5/5]Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
Percent out of range: -2147483648%
[STATUS] - Finalizing Video 100% [5/5]
```
