### ISSUE TITLE
[pre-release] 400 error downloading chat

### ISSUE THREAD

**Issue by Rowan-Paul** [lay295/TwitchDownloader#340] opened 2022-08-04 07:38 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

Downloading a video works fine on the pre-release, but when trying to download chat I get a 400 Bad Request:

`ERROR: The remote server returned an error: (400) Bad Request.`
![image](https://user-images.githubusercontent.com/46132597/182791279-2fb0afa5-3c99-488b-86a2-8f5ff1b11881.png)

 Using the stable release it works just fine. Tried with both JSON & the new HTML outputs and multiple videos.

**Comment by Magreal220** [comment] 2022-08-04 14:25
You must put the number "1" in the "Connections" section using the arrows in the box, not manually

**Comment by Oondanomala** [comment] 2022-08-04 15:49
Duplicate of #322, set the chat connections to 1

**Comment by Rowan-Paul** [comment] 2022-08-06 09:22
Thanks, that seems to have fixed it. But now when I try to render the chat I get a 404 error

**Comment by Oondanomala** [comment] 2022-08-06 09:33
To me, the new release used to do that every time i tried to download a chat.
But now that i try it again it works. ¯\_(ツ)_/¯
Try [this release](https://github.com/lay295/TwitchDownloader/releases/tag/1.40.9) or if that doesn't work too try the one before that

**Comment by Rowan-Paul** [comment] 2022-08-06 09:44
Ah, I'll try it a few more times later to see if it fixes itself 😊.

**Comment by Raikiry** [comment] 2022-08-29 16:06
where I should set chat connections to 1 ?

**Comment by ScrubN** [comment] 2023-01-31 06:00
> Thanks, that seems to have fixed it. But now when I try to render the chat I get a 404 error

I believe that was FFZ changing their backend. Both that and the original issue should be fixed

**Comment by Rowan-Paul** [comment] 2023-01-31 08:03
Yes it's working great!

**Comment by ScrubN** [comment] 2023-01-31 08:08
Oops. Github mobile sucks

**Closed by ScrubN** 2023-01-31 08:08 UTC
Labels: bug
