### ISSUE TITLE
Ability to download Chat on VODS over 24 hours?

### ISSUE THREAD

**Issue by Ecdldaiiere** [lay295/TwitchDownloader#720] opened 2023-05-24 13:19 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Currently downloading Chat seems to be limited to the first 24 hours. I have a VOD that is 47 hours long that I want to download chat from, but unable to do so. Would be nice if i could.

**Comment by ScrubN** [comment] 2023-05-24 21:32
I assume this is an artifact of #719 where the API is returning your vod of choice as having a 0 second duration

**Comment by ScrubN** [comment] 2023-05-28 03:16
I'm unable to reproduce chat downloads being limited to 24 hours. Tested with a 44 hour VOD.

**Comment by ScrubN** [comment] 2023-07-16 05:23
Closing due to age and inability to reproduce

**Closed by ScrubN** 2023-07-16 05:23 UTC
Labels: bug, debugging
