### ISSUE TITLE
Downloads will never finish/pass the "encoding metadata" stage

### ISSUE THREAD

**Issue by RubenRME** [lay295/TwitchDownloader#914] opened 2023-12-11 19:47 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Cancelling the download will throw an error saying the output file "is being used by another process". Only after quitting the entire program the file is accessible by the video player.

Steps to reproduce:
1. Start downloading any clip
2. watch it progress past download
3. Observe it hang at encoding metadata

**Comment by HayleTechnica** [comment] 2023-12-13 20:36
I am having the same issue, thought I only use the mass downloader. The download reaches 100% but seems to be unable to begin the transcode with FFMPEG because of the file access issue. Attempting to delete a file before closing twitch downloader gives the message that it is being used by FFMPEG but task manager shows no CPU or GPU utilization for the FFMPEG process running under twitch downloader.

![image](https://github.com/lay295/TwitchDownloader/assets/55044085/53d6154d-303d-45c1-8b36-830391cc621e)

**Comment by ScrubN** [comment] 2023-12-14 05:46
> Attempting to delete a file before closing twitch downloader gives the message that it is being used by FFMPEG

This is very good information. I will capture the log output from FFmpeg and write it to a file, and I will need you to test it via a workflow build since I cannot reproduce the issue. Does this sound alright?

**Comment by 2904nando** [comment] 2023-12-19 01:39
Same problem here. I updated from another version and it just hangs on "Encoding Clip Metadata 0%". Cancelling and trying to delete the file throws an error that the file is being used. Forcing the ffmpeg process to end allows me to delete the file, but couldn't make it work.

**Comment by 2904nando** [comment] 2023-12-19 01:52
Something that may be a "workaround" for those stuck with this error. When you get stuck at "Encoding Clip Metadata 0%", closing the TwitchDownloader unlocked the file and saved it normally. Maybe this can also be a nice debugging point for the devs.

**Comment by HayleTechnica** [comment] 2023-12-20 09:49
> > Attempting to delete a file before closing twitch downloader gives the message that it is being used by FFMPEG
> 
> This is very good information. I will capture the log output from FFmpeg and write it to a file, and I will need you to test it via a workflow build since I cannot reproduce the issue. Does this sound alright?

I can do that no problem

**Comment by TheInevitableBug** [comment] 2023-12-30 00:54
Turning off 'Encode Metadata' in the clip download menu allows clips to download in the task queue

**Comment by ScrubN** [comment] 2023-12-30 05:19
I might have discovered the problem...
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/cea698c4-4f93-424b-b6a8-493c5df0a5fb)

**Comment by ScrubN** [comment] 2024-01-05 02:46
Sadly #922 did not fix the problem, as I just experienced it while debugging a different feature. I was able to output a verbose log from FFmpeg, however I was unable to come to any useful conclusions. If any FFmpeg wizards are in this thread, you are welcomed to help interpret the log file: [ffmpeg-20240104-210417.log](https://github.com/lay295/TwitchDownloader/files/13837286/ffmpeg-20240104-210417.-.Copy.log)

In the meantime, I will be adding a 30 second timeout on the encoding metadata stage.

**Comment by ScrubN** [comment] 2024-01-05 02:57
To make matters stranger, the mp4 file of the last clip was written entirely and FFmpeg seemed to just lock up? I just experienced the issue again with a different clip, and this one only wrote 75 bytes before stopping: [ffmpeg-20240104-215045 - Copy.log](https://github.com/lay295/TwitchDownloader/files/13837504/ffmpeg-20240104-215045.-.Copy.log)
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/0d5a4206-14bb-4162-9f26-fdc9a9849731)

**Comment by ScrubN** [comment] 2024-01-05 03:53
I have solved the issue. We were redirecting stderr, but we did not call `BeginErrorReadLine()`, which caused FFmpeg to lock up until TwitchDownloaderWPF was closed, but only sometimes?

**Closed** 2024-01-05 06:56 UTC
Labels: bug
