### ISSUE TITLE
Badges 404 chat rendering error

### ISSUE THREAD

**Issue by asedim** [lay295/TwitchDownloader#710] opened 2023-05-18 19:07 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Looks like Twitch murdered badges API endpoint causing chat rendering to fail 🙁 

```
[STATUS] - Fetching Images [1/2]Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at TwitchDownloaderCore.TwitchHelper.GetChatBadgesData(List`1 comments, Int32 streamerId, CancellationToken cancellationToken)
   at TwitchDownloaderCore.TwitchHelper.GetChatBadges(List`1 comments, Int32 streamerId, String cacheFolder, EmbeddedData embeddedData, Boolean offline, CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatRenderer.GetScaledBadges(CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatRenderer.FetchScaledImages(CancellationToken cancellationToken)
   at TwitchDownloaderCore.ChatRenderer.RenderVideoAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.RenderChat.Render(ChatRenderArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Aborted (core dumped)
```

```
$ curl https://badges.twitch.tv/v1/badges/global/display -I
HTTP/2 404
date: Thu, 18 May 2023 18:59:00 GMT
vary: Origin
```

**Comment by lay295** [comment] 2023-05-18 19:41
Duplicate of #674, I'll work again in a few hours.

I'll try and migrate to the GQL or official API this weekend

**Closed by lay295** 2023-05-18 19:41 UTC
Labels: bug
