### ISSUE TITLE
FFmpeg does not support paths that include emoji.

### ISSUE THREAD

**Issue by Mishasama** [lay295/TwitchDownloader#1271] opened 2024-12-25 16:28 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

![image](https://github.com/user-attachments/assets/f69a23a4-0b67-4a59-ad4c-2c04834c8139)
When the VOD's title include emoji, the FFmpeg will fail. Because the filename is auto set by the templates.

### Add any related files or extra information here

Sample: 🎅🎄

**Comment by Mishasama** [comment] 2024-12-25 16:29
And... Have you noticed that the path contains a lot of duplicate folders with the same name?

**Comment by superbonaci** [comment] 2024-12-25 18:21
There's been a recent issue with the Linux kernel and emoji in filesystem names, maybe that affects TwitchDownloader?

[Linux Fixes Regression That Broke File Names With ❤️ & Other Special Characters](https://www.phoronix.com/news/Linux-Reverts-Special-Char-Uni)

**Comment by ScrubN** [comment] 2024-12-26 01:43
The regression was the first thing I thought of when I saw the email notification, however it only affected _some filesystems_ on Linux, however Misha is not even using Linux so the regression is not relevant.

**Comment by ScrubN** [comment] 2024-12-26 01:44
> And... Have you noticed that the path contains a lot of duplicate folders with the same name?

I have no clue how that happened, however that's more likely the culprit than the emojis. I'll look into that.

**Comment by Mishasama** [comment] 2024-12-26 23:55
> There is no possible way for the working directory to repeat so many times.

![image](https://github.com/user-attachments/assets/a558d284-e621-469b-86ae-142ddded5f2c)
![image](https://github.com/user-attachments/assets/b10086c6-80af-4758-b573-71a949ba4f30)

No, it actually happened. It was in the temp folder.

**Comment by superbonaci** [comment] 2024-12-27 15:19
@Mishasama It may be some issue with your character encoding of the operating system. If you install the language package and switch to english does still happen?

**Comment by ScrubN** [comment] 2024-12-27 17:43
Oh I see, you clicked "retry" in the task queue after the task failed.

**Comment by ScrubN** [comment] 2024-12-28 02:23
@Mishasama can you try again with the newest commit and see if it still occurs? If so, can you share the VOD ID? I have downloaded several VODs with emojis in the name before and never encountered any issues.

**Comment by superbonaci** [comment] 2024-12-28 20:12
Here are some screenshots of the 2 videos I downloaded, one selecting the destination manually and the other added to batch:
- [I had McDonalds today and boy.... am I feeling it 🤢🤢🤢 | TKN -> Marvel Rivals Ranked??](https://www.twitch.tv/prayerhandemoji_/video/2334526378)
- [my way #1 - 私の道#0🐱‍👤](https://www.twitch.tv/emojicore74/video/2334464594)

**Comment by superbonaci** [comment] 2024-12-28 20:20
Here are some screenshots of the 2 videos I downloaded, one selecting the destination manually and the other added to batch:
- [I had McDonalds today and boy.... am I feeling it 🤢🤢🤢 | TKN -> Marvel Rivals Ranked??](https://www.twitch.tv/prayerhandemoji_/video/2334526378)
- [my way #1 - 私の道#0🐱‍👤](https://www.twitch.tv/emojicore74/video/2334464594)

![WPF1](https://github.com/user-attachments/assets/390c100a-936e-4891-bf9a-7a122614f8c9)

![WPF2](https://github.com/user-attachments/assets/b2274279-47f4-4364-8bac-08a2afbbdc66)

![WPF3](https://github.com/user-attachments/assets/0d37721b-a1ef-428e-b350-13ef958b30ba)

The 2 videos downloaded correctly but the first one had some characters renamed:

![WPF4](https://github.com/user-attachments/assets/8bb7147a-b662-4e4c-9295-255bc70ca7f0)

**Comment by superbonaci** [comment] 2024-12-28 20:24
I think this issue can be closed as fixed.

**Comment by Mishasama** [comment] 2024-12-28 20:52
> @Mishasama can you try again with the newest commit and see if it still occurs? If so, can you share the VOD ID? I have downloaded several VODs with emojis in the name before and never encountered any issues.

Sadly, that VOD has been changed to subscription only and I can't download it any more. Maybe have to implement a way to get M3U8 by ID to download VOD. 😂

**Comment by superbonaci** [comment] 2024-12-28 21:12
@Mishasama that's not a problem if you subscribe to the channel, just for the sake of trying again. At least try now because may be deleted sometime.

**Comment by ScrubN** [comment] 2024-12-28 21:25
> Maybe have to implement a way to get M3U8 by ID to download VOD. 😂

Unfortunately I'm a fan of not having amazon lawyers on my doorstep.

Also, if a project as big as TD were to implement circumvention of subscription barriers, Twitch would likely patch the method very fast.

**Comment by ScrubN** [comment] 2024-12-28 21:26
@Mishasama If you still have the download cache from before when it failed, you can check the ffmpeg log to see why ffmpeg was failing.

**Comment by Mishasama** [comment] 2024-12-28 21:38
> @Mishasama If you still have the download cache from before when it failed, you can check the ffmpeg log to see why ffmpeg was failing.

Doesn't it clean up automatically? I can't seem to find any log in the reassigned temp directory.

**Comment by superbonaci** [comment] 2024-12-28 21:43
Yeh they are clean up except the folder `TwitchDownloader`. Try searching you Recycle Bin for files named `ffmpegLog.txt`. But I think if there's no error it clean them up.

**Comment by superbonaci** [comment] 2024-12-28 21:50
You can try with these that have the same emoji and no sub:

- [NINE SOLS BLIND :) 🎅🎅🎅🎄](https://www.twitch.tv/albinovevo/video/2337277348)
- [💥Freash Force Wipe💥🏹Time to hunt all BP's📜🌠No matter how hard or impossible it is💎never lose sight of your goal🐸✨](https://www.twitch.tv/videos/2243464506)

The videos have this name:

```
[12-27-24] AlbinoVEVO - NINE SOLS BLIND ：) 🎅🎅🎅🎄.mp4
[9-5-24] Greekgodx - 💥Freash Force Wipe💥🏹Time to hunt all BP's📜🌠No matter how hard or impossible it is💎never lose sight of your goal🐸✨.mp4
```

Both ok no error:

![WPF5](https://github.com/user-attachments/assets/51c88570-46e5-40f9-9f57-813fa991d196)

![WPF6](https://github.com/user-attachments/assets/2e28f540-1a9e-4939-8231-6815a959db84)

**Comment by ScrubN** [comment] 2024-12-28 21:51
> Doesn't it clean up automatically? I can't seem to find any log in the reassigned temp directory.

You're right, the error in your screenshot originated from Process.Start in C# instead of being an FFmpeg exit code, so the cache directory was not preserved :/

**Comment by ScrubN** [comment] 2024-12-28 21:53
Based on the examples provided by @superbonaci however, I think its safe to say this issue is likely resolved, or the issue was not actually because of the emojis.

**Comment by Mishasama** [comment] 2024-12-29 02:08
> You can try with these that have the same emoji and no sub:
> 
> * [NINE SOLS BLIND :) 🎅🎅🎅🎄](https://www.twitch.tv/albinovevo/video/2337277348)
> * [💥Freash Force Wipe💥🏹Time to hunt all BP's📜🌠No matter how hard or impossible it is💎never lose sight of your goal🐸✨](https://www.twitch.tv/videos/2243464506)


no error too
![image](https://github.com/user-attachments/assets/82f29742-d63e-4641-8664-83532d1d7ff0)
![image](https://github.com/user-attachments/assets/5b170cc5-6d4b-4c1b-b855-8cea6c14a7fa)
----
Is the cache directory bug also confirm fixed? If so, you can close this issue.

**Comment by ScrubN** [comment] 2024-12-29 02:21
> Is the cache directory bug also confirm fixed?

Yes, it should now be fixed

**Closed by ScrubN** 2024-12-29 02:22 UTC
Labels: bug
