### ISSUE TITLE
Embed Emotes button slightly broken

### ISSUE THREAD

**Issue by Bozzeh** [lay295/TwitchDownloader#190] opened 2021-06-16 10:51 UTC
Hey just a minor thing, when you open the program and go to chat downloader and go to tick the Embed Emotes checkbox (Advanced JSON), it appears disabled until you click on Simple Text, then back to Advanced JSON.

Thanks :)

**Comment by lay295** [comment] 2021-06-18 02:29
I'm unable to reproduce this, could you send a GIF or a video of this happening? Are you on the latest version?

![](https://i.imgur.com/6uDz1Nz.gif)

**Comment by Bozzeh** [comment] 2021-06-20 00:11
Ver 1.39.8:
![tdl-issue](https://user-images.githubusercontent.com/43806391/122658380-d3555900-d1af-11eb-8ede-bd3214c5ea96.gif)

**Comment by lay295** [comment] 2021-06-25 20:32
Yeah whoops, I only tested with VODs not clips which is why I couldn't reproduce it initially. Should be fixed in 1.39.10 now.

**Closed** 2023-01-31 04:50 UTC
