### ISSUE TITLE
Broken VOD video for full VODs

### ISSUE THREAD

**Issue by GaspacoZanis** [lay295/TwitchDownloader#1142] opened 2024-07-10 11:05 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

I am using v1.54.7 of the program, and it gives me weird bug.

When I try to download a Highlight, I can download audio, but video gets frozen very quickly.

For example, here is publicly available VOD: https://www.twitch.tv/videos/2166590043
And here I re-uploaded on YouTube the downloaded file, to understand what I am talking about: https://www.youtube.com/watch?v=udvgx1sT3Hs

As you can see - the video is not working correctly.

I have also given out to my friend to try to download, and it seems like we have the same issue.

What is even more odd, if I try to download just part of the highlight, like this: https://www.twitch.tv/videos/2166590043?t=00h00m01s , then video seemingly works fine after being downloaded.

Why does it break if I try to download full VOD?

### Add any related files or extra information here

https://www.twitch.tv/videos/2166590043

**Comment by ScrubN** [comment] 2024-07-10 14:53
This sounds like it may be a duplicate of #1139. Please see if this workflow build still exhibits the issue: https://github.com/lay295/TwitchDownloader/actions/runs/9868014298

**Comment by ScrubN** [comment] 2024-07-10 15:00
This issue is indeed a duplicate of #1139. The workflow build will fix it, however I will also be releasing the fix in an update later today.
![image](https://github.com/lay295/TwitchDownloader/assets/72096833/23f3feda-5276-4976-b411-8c3880064cc9)

**Comment by ScrubN** [comment] 2024-07-11 02:26
The issue should be fixed in 1.54.8

**Closed by ScrubN** 2024-07-11 02:26 UTC
Labels: bug
