### ISSUE TITLE
Once the download reaches 99% it stays there and doesn't finish

### ISSUE THREAD

**Issue by GkWbn** [lay295/TwitchDownloader#749] opened 2023-06-29 13:53 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates

### Write stuff here

I'm not sure if it's a bug or not, but it already happend multiple times trying to download a twitch vod. I would be nice if i could get it to work properly because i'm that twitch streamers editor and he can't always send me all the streams.

![Twitch Downloader v1 53 0 29 06 2023 15_52_40](https://github.com/lay295/TwitchDownloader/assets/138132550/7214f816-0b00-4fca-b2ac-fde652a15e52)

**Comment by cordmouse** [comment] 2023-07-01 23:24
Same issue as described above, the download gets stuck at some random .ts segment showing 99%. When tried to clean folder and delete the segments windows was saying it was 3931.ts out of some 4500 segments in use.
Running the vod downloading again finishes correctly.

Hope the Verbose errors I have now enabled will help in the future.
I remember had the same problems with twitch downloader years ago.
Also naming the downloaded segments from the playlist with 4 leading zeros explicitly in the file name instead from simply 0 - so 0000.ts, 0001.ts would help with concatenating the segments in the download folder instead of needing to rename them prior to concat in a loop in ffmpeg under windows.
thanks for continuously developing the software.

**Comment by ScrubN** [comment] 2023-07-16 05:49
This is a duplicate of #265 and is being tracked there. Ideally this will be fixed in the next update but no promises since I cannot reproduce it myself.

> Also naming the downloaded segments from the playlist with 4 leading zeros explicitly in the file name instead from simply 0 - so 0000.ts, 0001.ts would help with concatenating the segments in the download folder instead of needing to rename them prior to concat in a loop in ffmpeg under windows.

The video parts files are given the same names they hold in Twitch API which is very convenient for us in several ways.
I plan to implement #544 eventually which will be a far superior solution to users merging the cache by hand.

**Closed by ScrubN** 2023-07-16 05:49 UTC

**Comment by riahc3** [comment] 2023-07-21 22:37
Not fixed. Still happening

**Comment by ScrubN** [comment] 2023-07-21 22:39
> Not fixed. Still happening

Read my comment again please.
