### ISSUE TITLE
Cannot download VOD - downloading gets stuck at the very end

### ISSUE THREAD

**Issue by Templayer** [lay295/TwitchDownloader#537] opened 2023-02-05 13:00 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

If I try downloading this VOD - https://www.twitch.tv/videos/1727120503
-- it gets stuck at the very end of the Downloading phase.

I've been using this software for over a year (I think), and I haven't changed much (i.e. there hasn't been a change in version since the last time that worked, etc.).

Does this happen to you guys?

Can't see a log file in the application's folder, and I'm too lazy to go hunting for it elsewhere.

I've tried it two times at this point - one time, I waited for about 4 hours, and then I tried restarting everything and letting it go overnight. After more than 12 hours, there was no progress. It's just stuck.

There is plenty of space on the harddrive, both for the destination folder and the temp/cache folder (both are on the same partition...)

**Comment by ScrubN** [comment] 2023-02-05 18:09
I assume it got stuck at 99%? Did the log say anything about "Video part ### failed after 10 retries"?

**Comment by Templayer** [comment] 2023-02-06 08:18
> I assume it got stuck at 99%? Did the log say anything about "Video part ### failed after 10 retries"?

There is no log in the folder with TwitchDownloader. If logs get stored elsewhere, I need to be told the path. I know I could go searching for it somewhere (either on my computer or here), but I'm too lazy. :P         

I think it got stuck at 99%, but I cannot be sure, due to https://github.com/lay295/TwitchDownloader/issues/536

**Comment by ScrubN** [comment] 2023-02-06 08:30
The log is on the right side of the GUI window. Logging to a file is on the todo list but not a high priority.

If the progress bar looked filled enough to infer that it was stuck at or around 99% then I will label this as a duplicate of #265. Further discussions will take place there

**Closed by ScrubN** 2023-02-06 08:30 UTC
Labels: bug
