### ISSUE TITLE
TwitchDownloader downloads the VOD, puts it together and then never outputs the complete video (as in it never gives me the complete file)

### ISSUE THREAD

**Issue by DieHardjagged** [lay295/TwitchDownloader#550] opened 2023-02-20 23:54 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Im using the newest version of TwitchDownloader and this never happened before, i downloaded a vod (1733138074) via direct download and then via enqueue option (when i noticed the first time that i never got a complete video) and both times, the Program puts the files together and never actually outputs a videofile.

**Comment by ScrubN** [comment] 2023-02-20 23:58
Sounds like a duplicate of #541

**Closed** 2023-02-20 23:58 UTC
Labels: bug
