### ISSUE TITLE
1.50 vs 1.40 Rendering Time

### ISSUE THREAD

**Issue by Reimaginated** [lay295/TwitchDownloader#456] opened 2022-12-09 18:28 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates

### Write stuff here

Was wondering why the newer versions have twice as long of chat rendering time for the same .JSON files. Same settings including file codec, size, and file format (MP4 H264). It's almost exactly doubled in the newer versions where I rendered in 1.40.7 in 15 minutes and in the latest (1.50.6) and it takes 33 minutes. Have tried NVIDIA H264 and H265 on 1.50.6 and are around the same time. Thanks.

**Comment by ScrubN** [comment] 2022-12-09 19:27
If your culture uses commas as a decimal separator, '0,5', then this is a duplicate of #388 and was fixed in 1.50.7 pre-release

**Comment by Reimaginated** [comment] 2022-12-09 20:25
> If your culture uses commas as a decimal separator, `0,5`, then this is a duplicate of #388 and was fixed in 1.50.7 pre-release

Nope, update time is 1.0 for both 1.50.6 and 1.40.7. Tried 1 and 1.0.

**Comment by ScrubN** [comment] 2022-12-09 20:32
Please upload your chat file. Github doesn't allow jsons so you'll have to rename the extension to .txt

**Comment by Reimaginated** [comment] 2022-12-09 20:43
[Test.txt](https://github.com/lay295/TwitchDownloader/files/10197989/Test.txt)
It's quite long, but still. I've tried: 1, 1.0, and 10.0 for Update Times and all of the Codecs but 1.40.x seems to render faster than 1.50.x on the same settings.

**Comment by ScrubN** [comment] 2022-12-10 08:11
I can confirm that rendering in 1.50.7 is slower than 1.40.7. I'm not sure how possible it is to reduce render times even further, however I managed to reduce render times by up to 10% with just 1 line change. Additionally, there is a further <1% reduced render time due to some other changes I made the other day.

I may try and look further into it, but as it stands ~90% of the render time is spent drawing text with the graphics library. I have thought about rewriting the render pipeline to add an OpenGL option in addition to the existing CPU rendering, but that's a BIG task.

**Comment by ScrubN** [comment] 2022-12-11 08:09
I have bad news. I was comparing to the wrong time, it's more like 3% faster instead of 11% :(

I'm really not sure what else I can squeeze out, we're primarily limited by the text/image rendering library. I could add an option to disable emojis since those are still ~7% of CPU time even after further optimizing the function. I made some major improvements to some parts of the renderer that would theoretically run >100x faster, but that makes very little difference when it would already take less than 10ms to run.

>90% of CPU time is spent on the rendering library or writing to ffmpeg. I've take a peek at the 1.40.7 renderer but that code is even more spaghetti than the current renderer. Odds are its faster because it has less features anyways.

**Comment by lay295** [comment] 2022-12-11 20:58
The reason for the slower stuff, is because on the previous version I always had to generate a new frame and I used information from the previous frame to generate the new frame. It was faster, but if I wanted just frames 80-90 I had to also generate frames 1-80 to get there.

I didn't realize just HOW much faster DrawText was vs DrawShapedText @ScrubN . It's just for RTL languages that need to "shape" their text. I know the try/catch block is stupid but if I try and determine when I need to call it more smartly instead of every time. There are also other performance things I can probably do just haven't had too much time to.

**Comment by ScrubN** [comment] 2022-12-11 21:01
> I didn't realize just HOW much faster DrawText was vs DrawShapedText @ScrubN . It's just for RTL languages that need to "shape" their text. I know the try/catch block is stupid but if I try and determine when I need to call it more smartly instead of every time.

So is it safe for me to do this:
```cs
if (isRtl)
{
    sectionImageCanvas.DrawShapedText(drawText, drawPos.X, drawPos.Y, textFont);
}
else
{
    sectionImageCanvas.DrawText(drawText, drawPos.X, drawPos.Y, textFont);
}
```

**Comment by lay295** [comment] 2022-12-11 21:03
@ScrubN Yeah that should be fine, might be even able to narrow it down even more with like a regex for only languages with shaped text? But might not be worth it

**Comment by ScrubN** [comment] 2022-12-11 21:04
Oh actually now that you say that I should use a regex to make sure the entire drawText does not contain any RTL

**Comment by lay295** [comment] 2022-12-11 21:28
> Oh actually now that you say that I should use a regex to make sure the entire drawText does not contain any RTL

I'm just going to push the isRtl above so I can release 1.50.8, feel free to change it to regex or make the check smarter :) but that combined with the update frame change I just made seems to make the render times better.

**Comment by ScrubN** [comment] 2022-12-11 22:46
Also for @Reimaginated, after lay added frame reuse (7e8d4fa) and I added regex to use the faster text drawing (0a081ac), rendering has gone from ~24x in 1.50.7 to ~42x. Still not the ~60x in 1.40.7 but it's much better

**Closed** 2022-12-13 17:49 UTC
