### ISSUE TITLE
Problem with VODs over 24h long

### ISSUE THREAD

**Issue by xaolin** [lay295/TwitchDownloader#48] opened 2020-08-05 19:34 UTC
I'm trying to download a part of a 24h+ long VOD and it only lets me download from what's over 24h. For example if the VOD is 25h:30mins long, I can only download 1h:30mins from it.

**Comment by lay295** [comment] 2020-08-06 00:00
It seems to be a UI bug, you can still download the full length VOD. Will be fixed in the next version.

**Comment by xaolin** [comment] 2020-08-06 05:08
How can I download the full length VOD? I'm getting an error when pressing download

**Comment by lay295** [comment] 2020-08-06 05:12
What error specifically? Also could you give a URL so I can try and reproduce the issue.

**Comment by xaolin** [comment] 2020-08-06 05:38
![image](https://user-images.githubusercontent.com/60317048/89495053-19841280-d7c0-11ea-90bf-0a95f83be5ff.png)
VOD link: https://www.twitch.tv/videos/45181799

**Comment by lay295** [comment] 2020-08-06 05:39
Oh didn't know you were cropping it as well. I'll have an update out soon to fix it.

**Comment by xaolin** [comment] 2020-08-06 05:42
Alright. Thanks!

**Comment by lay295** [comment] 2020-08-09 04:08
Should be fixed in [1.3 beta](https://github.com/lay295/TwitchDownloader/releases/tag/1.30-beta). Let me know if it's not, thanks for the report.

**Closed by lay295** 2020-08-09 04:08 UTC
