### ISSUE TITLE
Cannot Choose Quality 

### ISSUE THREAD

**Issue by REALtony4twenty** [lay295/TwitchDownloader#386] opened 2022-10-26 20:51 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

I created a tutorial video on youtube for this and a user is experiencing an issue where the quality option box remains blank and there are no options to choose from. I tried the same link to the same VOD and was not experiencing the same issue and I check that we were using the same version. 
![EAE50520-2340-4340-9E7D-A1862E6739E2](https://user-images.githubusercontent.com/101494591/198135080-70f64731-8c69-4b54-b023-3b2b91680967.jpg)
![E331CE44-18CD-4985-A722-32B4F15124A6](https://user-images.githubusercontent.com/101494591/198135086-9cae8655-9f91-4a1f-ab0e-ffa4d20cd4d0.jpg)
![unknown](https://user-images.githubusercontent.com/101494591/198135092-717cd211-db6d-4897-86d1-8d52962bbf4d.png)

**Comment by ScrubN** [comment] 2022-10-27 20:51
Have the user clear their cache in settings and redownload the program. I'm unable to reproduce with the VOD shown on my end.

**Comment by ScrubN** [comment] 2023-02-11 00:15
Closing due to age

**Closed by ScrubN** 2023-02-11 00:15 UTC
Labels: bug
