### ISSUE TITLE
Downloaded files do not exist

### ISSUE THREAD

**Issue by AngryAlienSpaceship** [lay295/TwitchDownloader#541] opened 2023-02-09 23:00 UTC
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

As soon as I downloaded the latest update (v.1.51.2), when I tried to download a section of a vod, it said "ERROR: Could not find a path "C:\Users\ (my name) \AppData\Local\Temp\TwitchDownloader"
I created the folder "TwitchDownloader" and downloaded things there, and it worked, but when I checked that folder, there was nothing there. I tried again, and I saw that while the dowload was going on, a new folder full with parts of the video were being added, but as soon as the download ended, they were gone.
I tried uninstalling and installing again, but it didn't work

https://user-images.githubusercontent.com/124939429/217958195-787ee9e6-d3a6-4dc8-85d8-fde00be2fdda.mp4

Thanks for reading

**Comment by ScrubN** [comment] 2023-02-09 23:32
`C:\Users\[you]\AppData\Local\Temp\TwitchDownloader` is where the temporary download cache is stored. The final download in your screen recording should be at `C:\Users\[you]\Desktop\Rafa\TwitchDownloader\asd.mp4`.

**Comment by AngryAlienSpaceship** [comment] 2023-02-10 00:53
I tried again, but the issue isn't fixed

**Comment by ScrubN** [comment] 2023-02-10 01:25
When you say you tried again, does that mean you were looking at the destination you saved to or you are looking at the cache again?

**Comment by ScrubN** [comment] 2023-02-10 02:05
Well the cache is cleared after every run. I don't see why there is no downloaded video though though. Maybe try resetting the ffmpeg arguments?

**Comment by DailyTwitch** [comment] 2023-02-10 02:23
same here, updated to a newer version, the downloaded file doesn't exist.

**Comment by ScrubN** [comment] 2023-02-10 03:06
Interesting. I don't really know what to say, I'm able to download https://twitch.tv/videos/1732383117 both with and without cropping.

For now I guess I'll revert the release back to pre-release

**Comment by dfg555** [comment] 2023-02-10 03:23
Chat render stopped working with this update as well.

**Comment by ScrubN** [comment] 2023-02-10 03:27
> Chat render stopped working with this update as well.

Please [create a new issue](https://github.com/lay295/TwitchDownloader/issues/new?assignees=&labels=bug&template=bug_report.yaml) explaining what stopped working.

**Comment by AngryAlienSpaceship** [comment] 2023-02-10 12:02
> Interesting. I don't really know what to say, I'm able to download https://twitch.tv/videos/1732383117 both with and without cropping.
> 
> For now I guess I'll revert the release back to pre-release

Thank you, now is working again

**Comment by ScrubN** [comment] 2023-02-10 21:12
> > Interesting. I don't really know what to say, I'm able to download https://twitch.tv/videos/1732383117 both with and without cropping.
> > For now I guess I'll revert the release back to pre-release
> 
> Thank you, now is working again

Sooo, videos are downloading again? It is possible the issue was that you needed to reboot your computer?

**Comment by goldbattle** [comment] 2023-02-11 00:58
I had to manually create my directory to get this to work. Once it was created, it worked as long as I don't change the temp directory.
```
mkdir /tmp/tvc_single_video/TwitchDownloader
```


Command:
```
/mnt/twitchvods2/twitch_vod_creator/thirdparty/Twitch_Downloader_1.51.2/TwitchDownloaderCLI 
    videodownload 
    --id 1704777050 
    --ffmpeg-path "/mnt/twitchvods2/twitch_vod_creator/thirdparty/ffmpeg-4.3.1-amd64-static/ffmpeg" 
    --temp-path "/tmp/tvc_single_video/" 
    --quality 1080p60 
    -o /mnt/twitchvods2/twitch_vod_creator/../data//simply/2023-01/1704777050.mp4
```


Error I see:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not find a part of the path '/tmp/tvc_single_video/TwitchDownloader'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/tvc_single_video/TwitchDownloader'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String , Boolean )
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String , Boolean , EnumerationOptions )
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 , Boolean )
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String , FindTransform , EnumerationOptions , Boolean )
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String , FindTransform , EnumerationOptions )
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at System.IO.Directory.GetDirectories(String , String , EnumerationOptions )
   at System.IO.Directory.GetDirectories(String )
   at TwitchDownloaderCore.TwitchHelper.CleanupUnmanagedCacheFiles(String cacheFolder)
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadVideo.Download(VideoDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Aborted (core dumped)
```


I think this was fixed in https://github.com/lay295/TwitchDownloader/commit/a67d01ebc640dea67b2e1afdbdf2dc1382a3c338 correct @ScrubN ?

**Comment by ScrubN** [comment] 2023-02-11 01:00
> I had to manually create my directory to get this to work. Once it was created, it worked as long as I don't change the temp directory.
> 
> ```
> mkdir /tmp/tvc_single_video/TwitchDownloader
> ```
> 
> Command:
> 
> ```
> /mnt/twitchvods2/twitch_vod_creator/thirdparty/Twitch_Downloader_1.51.2/TwitchDownloaderCLI 
>     videodownload 
>     --id 1704777050 
>     --ffmpeg-path "/mnt/twitchvods2/twitch_vod_creator/thirdparty/ffmpeg-4.3.1-amd64-static/ffmpeg" 
>     --temp-path "/tmp/tvc_single_video/" 
>     --quality 1080p60 
>     -o /mnt/twitchvods2/twitch_vod_creator/../data//simply/2023-01/1704777050.mp4
> ```
> 
> Error I see:
> 
> ```
> Unhandled exception. System.AggregateException: One or more errors occurred. (Could not find a part of the path '/tmp/tvc_single_video/TwitchDownloader'.)
>  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/tvc_single_video/TwitchDownloader'.
>    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String , Boolean )
>    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
>    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String , Boolean , EnumerationOptions )
>    at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 , Boolean )
>    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String , FindTransform , EnumerationOptions , Boolean )
>    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String , FindTransform , EnumerationOptions )
>    at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String , String , EnumerationOptions )
>    at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
>    at System.IO.Directory.GetDirectories(String , String , EnumerationOptions )
>    at System.IO.Directory.GetDirectories(String )
>    at TwitchDownloaderCore.TwitchHelper.CleanupUnmanagedCacheFiles(String cacheFolder)
>    at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
>    at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
>    at System.Threading.Tasks.Task.Wait()
>    at TwitchDownloaderCLI.Modes.DownloadVideo.Download(VideoDownloadArgs inputOptions)
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at TwitchDownloaderCLI.Program.Main(String[] args)
> Aborted (core dumped)
> ```
> 
> I think this was fixed in [a67d01e](https://github.com/lay295/TwitchDownloader/commit/a67d01ebc640dea67b2e1afdbdf2dc1382a3c338) correct @ScrubN ?

It has been fixed, correct

**Comment by DieHardjagged** [comment] 2023-02-21 00:02
Hm, alright, i think i will just redownload the program and see if it works.

**Comment by ScrubN** [comment] 2023-02-21 00:04
> Hm, alright, i think i will just redownload the program and see if it works.

You mentioned enqueuing. Did you only try the task queue?
Also do you know how to check what version of ffmpeg is being used? Perhaps its an issue with specific ffmpeg builds.

**Comment by DieHardjagged** [comment] 2023-02-21 00:05
> > Hm, alright, i think i will just redownload the program and see if it works.
> 
> You mentioned enqueuing. Did you only try the task queue? Also do you know how to check what version of ffmpeg is being used? Perhaps its an issue with specific ffmpeg builds.

I tried both the task queue and enqueueing, i never changed anything from the ffmpeg folder since i first used the program.

**Comment by ScrubN** [comment] 2023-02-21 00:12
> Interesting, i never noticed that you have a prelease of 1.51.2 i will test that one too.

So the issue isn't limited to 1.51.2. Good to know

> Alright, i guess redownloading the same version fixed this problem, my temp folder that used to have the Twitch Emotes is still empty though

Wait so are you downloading the VOD itself or its chat?

**Comment by DieHardjagged** [comment] 2023-02-21 00:13
> > Interesting, i never noticed that you have a prelease of 1.51.2 i will test that one too.
> 
> So the issue isn't limited to 1.51.2. Good to know
> 
> > Alright, i guess redownloading the same version fixed this problem, my temp folder that used to have the Twitch Emotes is still empty though
> 
> Wait so are you downloading the VOD itself or its chat?

I always download the VOD and the Chat and usually render the Chat a couple hours later with the added Timestamps option.

**Comment by ScrubN** [comment] 2023-02-21 00:31
> Alright, i guess redownloading the same version fixed this problem

When you originally downloaded it, did you just use the auto updater/replace the current files, and when you redownloaded it just now was it a completely fresh install? If yes to both then perhaps the issue is specific builds of ffmpeg?

**Comment by DieHardjagged** [comment] 2023-02-21 00:35
> > Alright, i guess redownloading the same version fixed this problem
> 
> When you originally downloaded it, did you just use the auto updater/replace the current files, and when you redownloaded it just now was it a completely fresh install? If yes to both then perhaps the issue is specific builds of ffmpeg?

Whenever i download a new build, i delete the current folder and replace it with the new one, the ffmpeg folder always remains untouched because it worked flawless before this problem.

**Comment by ScrubN** [comment] 2023-02-21 00:43
Maybe the older versions did, but the current version does not have an ffmpeg folder. Instead everything ffmpeg is downloaded to the application directory. Though with you wiping the contents every time you update, it clears my suspicion of ffmpeg being the problem
![image](https://user-images.githubusercontent.com/72096833/220219574-de30bca2-622a-4aec-af2d-1a826ec8727f.png)

**Comment by DieHardjagged** [comment] 2023-02-21 00:45
I think i need to specify what i mean with "that ffmpeg folder remains untouched", because i have an folder called "ffmpeg-3.4.1-win64-static" on the drive that also has Twitch Downloader on it, but i cant remember anymore why its there.

**Comment by ScrubN** [comment] 2023-02-21 00:46
> Alright, it works again with 1.51.1, i will test it with 1.51.2 and just use that version if it works without a problem now.

I honestly have no clue then. I think I'll make some changes to not immediately clear the cache and retry finalizing if it failed the first few times. I'll probably also make it not clear the cache on error so we can also implement delayed retrying since several people have asked for it #544

**Comment by DieHardjagged** [comment] 2023-02-21 00:49
> > Alright, it works again with 1.51.1, i will test it with 1.51.2 and just use that version if it works without a problem now.
> 
> I honestly have no clue then. I think I'll make some changes to not immediately clear the cache and retry finalizing if it failed the first few times. I'll probably also make it not clear the cache on error so we can also implement delayed retrying since several people have asked for it #544

Its kinda strange that i got the problem now, given 1.51.1 worked without a problem last month.

**Comment by ScrubN** [comment] 2023-02-21 00:52
> I think i need to specify what i mean with "that ffmpeg folder remains untouched", because i have a separate folder called "ffmpeg-3.4.1-win64-static" on the drive that also has Twitch Downloader on it, but i cant remember anymore why its there.

Sounds like its a remnant from older versions that used an ffmpeg wrapper library instead of sending commands to the standalone program

> Its kinda strange that i got the problem now (until it was fixed again), given 1.51.1 worked without a problem last month.

I would guess that the issue is corrupted transport stream segments but I know for a fact that ffmpeg just ignores the garbage data when testing #494. This issue is honestly a mystery to me

**Comment by DieHardjagged** [comment] 2023-02-21 20:49
I was testing around with the queue option with 1.51.2 and if it set the download queue higher than 3 vods simultaneously, the videos wont render, but it still works if its kept under 3.

**Comment by DieHardjagged** [comment] 2023-02-21 22:24
I tried the URL List option in the Task Queue in Version 1.51.2, but i get the same issue as i did with 1.51.1 before it stopped, i get no video outputs, despite it claiming it was finished.

**Comment by ScrubN** [comment] 2023-02-21 23:43
> Unrelated to my problem, but how do i get back the entire emotes folder after i resetted it?

Emotes are fetched as they are needed, AKA embedding in downloads and rendering

**Comment by DieHardjagged** [comment] 2023-02-22 00:49
> > Unrelated to my problem, but how do i get back the entire emotes folder after i resetted it?
> 
> Emotes are fetched as they are needed, AKA embedding in downloads and rendering

Ok im starting to loose my mind, my problem is, i changed the path of the cache folder, but the program does not accept the new folder and still keeps putting everything into the default folder.

**Comment by ScrubN** [comment] 2023-02-22 01:29
> Alright that got solved for me, but im starting to loose my mind, because when i change the path of the cache folder, the program (as in 1.51.1) does not accept the new folder and still keeps putting everything into the default folder.

I'm unable to reproduce with both video download and chat render.

**Comment by DieHardjagged** [comment] 2023-02-22 01:44
> > Alright that got solved for me, but im starting to loose my mind, because when i change the path of the cache folder, the program (as in 1.51.1) does not accept the new folder and still keeps putting everything into the default folder.
> 
> I'm unable to reproduce with both video download and chat render.

Well, i guess for now i have to life with the temp folder being on C: until i find a way to fix it.
But i get more and more errors the more i try with 1.51.2, for example when i try to update a chat json that works in 1.51.1 i get this error when i try the same with 1.51.2.
![Screenshot 2023-02-22 024026](https://user-images.githubusercontent.com/62212036/220499358-35ddb9af-a572-468f-a769-7ce4e5507165.png)

**Comment by ScrubN** [comment] 2023-02-22 01:48
The chat extension check in 1.51.2 is accidentally case sensitive. Rename to `.json` and it will work.

**Comment by DieHardjagged** [comment] 2023-02-22 01:48
> The chat extension check in 1.51.2 is accidentally case sensitive. Rename to `.json` and it will work.

Oh my, i never noticed this, ok that explains it then.

**Comment by DieHardjagged** [comment] 2023-02-22 01:50
> The chat extension check in 1.51.2 is accidentally case sensitive. Rename to `.json` and it will work.

This is what i got when i renamed it from .Json to .json.

![Screenshot 2023-02-22 025024](https://user-images.githubusercontent.com/62212036/220500303-84a1d94e-9176-4aa3-8186-538c67b0cd29.png)

**Comment by ScrubN** [comment] 2023-02-22 01:53
> This is what i got when i renamed it from .Json to .json.
> 
> ![Screenshot 2023-02-22 025024](https://user-images.githubusercontent.com/62212036/220500303-84a1d94e-9176-4aa3-8186-538c67b0cd29.png)

Sounds like I forgot to add a check for when the chat contains no comments.

**Comment by DieHardjagged** [comment] 2023-02-22 01:55
> 

You mean as in no chatting comments? 
I rechecked the rendered file i created back then, its not an empty chat, at all.

**Comment by ScrubN** [comment] 2023-02-22 01:56
> > 
> 
> You mean as in no chatting comments? I rechecked the rendered file i created back then, its not an empty chat, at all.

Hmmm. Could you send the chat file?

**Comment by DieHardjagged** [comment] 2023-02-22 01:58
> > > 
> > 
> > 
> > You mean as in no chatting comments? I rechecked the rendered file i created back then, its not an empty chat, at all.
> 
> Hmmm. Could you send the chat file?

[[10-22-22] EarsOfKittyness - It's caturday night and psygnosis owl is calling my name - Chat.zip](https://github.com/lay295/TwitchDownloader/files/10799324/10-22-22.EarsOfKittyness.-.It.s.caturday.night.and.psygnosis.owl.is.calling.my.name.-.Chat.zip)

**Comment by ScrubN** [comment] 2023-02-22 02:07
> Sorry, the system did not accept the file by itself so i had to zip it.

Yes, I don't understand why Github dislikes json files.

It looks like the bug is an oversight when cleaning up at some point, I've fixed it for 1.51.3 which hopefully will be out in a few days

**Comment by MorbiusProductions** [comment] 2023-03-06 02:11
I'm using 1.52.0 and I'm having the same problem. I tell it to download the video to my Downloads folder but when it finishes and I open the Downloads folder it's not there. The file shows up in the Recent Files list of File Explorer but when I click the file it says it can't find it.

**Comment by ScrubN** [comment] 2023-03-07 07:12
I have added a condition where the cache will not be cleared if ffmpeg fails to finalize or the output file does not exist. A log file will also be generated in the cache directory to help see what the issue was with ffmpeg. I'll release it in 1.52.1 in a day or two along with some other bug fixes.

**Comment by ScrubN** [comment] 2023-08-23 03:17
Based on a lack of recent reports I am assuming this is fixed and am going to close the issue. If anyone experiences missing download files again please say so and I will reopen the issue.

**Closed by ScrubN** 2023-08-23 03:17 UTC
Labels: bug
