### ISSUE TITLE
99% stop

### ISSUE THREAD

**Issue by MonkeSmart** [lay295/TwitchDownloader#265] opened 2021-11-28 11:37 UTC
Hello there, my dude, can you add a cache recalculation for the downloaded data? Bro, this is quite unsatisfactory how often it gets stuck on 99% (especially on longer downloads), and the only way further is to close the program and fully re-download, even though data is already there, cached (for example, 3GB 12 sec. parts), now, this cache is unusable, and gets wiped out if you re-download. Cheers.
![scrsht](https://user-images.githubusercontent.com/92262906/143765858-251fc586-6b3f-47f9-814e-5adcf869a8e7.JPG)

**Comment by lay295** [comment] 2021-11-28 11:51
I'll try and address the 99% download issue eventually. It seems it's happening more recently and I haven't touched the downloading code in a long time. I assume one or a few parts are stuck downloading at super slow speeds either due to the users internet, or something with the Twitch servers.

I'll probably add some code to detect some slow straggler downloads which will address the root of the issue, but if I try and re-use previously downloaded segments as a "cache" it'll truly be a headache to detect and correct for corrupted video segments because the program was closed mid download.

I'm busy finishing up my final semester of college, and am busy applying for me first real developer job after I graduate, so I don't really have the motivation to work on this currently. Maybe in a month I'll have the time/motivation to fix and work on some stuff. If it happens often I'd recommend TwitchLeecher a try.

**Comment by MonkeSmart** [comment] 2021-11-28 12:00
Sure, my dude, take your time. Since this 99% issue exists, thought of giving you the idea of recalculating the hash like in uTorrent, instead of fixing the downloading code. Cheers.

**Comment by MonkeSmart** [comment] 2022-10-26 09:14
Hey, dude, nice to see you're back.
I see that you spam updates now (which is good),- logged in to remind you that 99% still exists,- it occurred recently multiple times.
Cheers.

**Comment by laotoet** [comment] 2022-12-03 04:57
I have the solution but I don't think it will work. You can try turning on and off the wifi or changing the network by turning the VPN on and off.

**Comment by laotoet** [comment] 2022-12-03 04:58
> I have the solution but I don't think it will work. You can try turning on and off the wifi or changing the network by turning the VPN on and off.

.

**Comment by laotoet** [comment] 2022-12-03 05:00
> Hey, dude, nice to see you're back. I see that you spam updates now (which is good),- logged in to remind you that 99% still exists,- it occurred recently multiple times. Cheers.

I have the solution and maybe it will work. You can try turning on and off the wifi or changing the network by turning the VPN on and off.

**Comment by TheWeakCheer** [comment] 2022-12-06 21:04
Same problem :(

**Comment by MonkeSmart** [comment] 2022-12-19 07:19
> I have the solution and maybe it will work. You can try turning on and off the wifi or changing the network by turning the VPN on and off.

It does not. You need to close the program and re-download, and the program will re-download from the start. This is why I asked for some recalculating system for the cache (since it is already there, pre-merged), so the program knows where to continue.

**Comment by lay295** [comment] 2022-12-19 08:29
When the next version is released you can try that. Switched from WebClient to HttpClient which might make some impact. If that doesn't work only other reasonable way would probably do some math and statistics to detect a straggler.



> Since this 99% issue exists, thought of giving you the idea of recalculating the hash like in uTorrent

I don't know what the hash of the file is supposed to be, and I don't think any web server returns that info so. Hard to tell if a downloaded file is corrupt or not.

**Comment by EroAxe** [comment] 2022-12-21 10:11
Just a quick bump, was checking this out since TwitchLeecher doesn't work anymore and I still get this 99% bug on the most recent version.

**Comment by WolfRider3000** [comment] 2023-01-13 13:26
I had the same issue today (on the last version 1.51.1). It got stuck on 97%, so I reopened the program, cleared the cache and started the download again, but this time it got stuck on 99%. I turned the Wi-Fi on and off and it seems to have helped (It started to merging parts together), but I'm not sure if the VoD is corrupted now or not, since I can't check the entire 12-hour VoD. So I don't know what to do now, should I re-download it or it's fine?

**Comment by goldbattle** [comment] 2023-02-05 01:58
This is very hard to debug, but if someone runs into the issue please post a link to the vod that has the problem.

**Comment by ScrubN** [comment] 2023-02-05 02:55
I believe this has been resolved in the next release

**Comment by ScrubN** [comment] 2023-02-06 08:34
If anyone runs into the problem again on 1.51.1 can see if it also occurs of 1.51.2 that would be appreciated. The downloader has been switched from WebClient to HttpClient which may or may not make a difference. Otherwise we'll have to implement a timeout for downloading parts.

**Comment by Templayer** [comment] 2023-02-06 09:19
For me, this happens everytime when trying to download this VOD - https://www.twitch.tv/videos/1727120503

**Comment by ScrubN** [comment] 2023-02-06 23:39
I'm almost certain the problem is with Twitch. I was able to successfully download [1727120503](https://www.twitch.tv/videos/1727120503) at full quality on 1.51.1, though I used only 1 download thread. I'll just add a 30s timeout anyways hopefully that'll fix it.

**Comment by lay295** [comment] 2023-02-06 23:51
> For me, this happens everytime when trying to download this VOD - https://www.twitch.tv/videos/1727120503

Just to clarify, still happening on 1.15.2?

**Comment by ScrubN** [comment] 2023-02-06 23:52
> Just to clarify, still happening on 1.15.2?

I think @Templayer said so. Even if they didn't it probably would because both HttpClient and WebClient default to infinite timeout

**Comment by Templayer** [comment] 2023-02-07 07:50
> > Just to clarify, still happening on 1.15.2?
> 
> I think @Templayer said so. Even if they didn't it probably would because both HttpClient and WebClient default to infinite timeout

The latest published version is 1.51.1 [Latest](https://github.com/lay295/TwitchDownloader/releases/latest). That is the one I have used.

**Comment by ScrubN** [comment] 2023-02-07 07:54
> > > Just to clarify, still happening on 1.15.2?
> > 
> > 
> > I think @Templayer said so. Even if they didn't it probably would because both HttpClient and WebClient default to infinite timeout
> 
> The latest published version is 1.51.1 [Latest](https://github.com/lay295/TwitchDownloader/releases/latest). That is the one I have used.

I see. Make sure it still happens on 1.51.1 then try [1.51.2](https://github.com/lay295/TwitchDownloader/releases/tag/1.51.2)

**Comment by Endosxn** [comment] 2023-04-01 08:56
Yeah, 31/03/23 I was downloading a VOD at 10 Threads and it got stuck on 99%. I was using v1.52.2 on Windows GUI

**Comment by Templayer** [comment] 2023-04-01 09:57
> Yeah, 31/03/23 I was downloading a VOD at 10 Threads and it got stuck on 99%. I was using v1.52.2 on Windows GUI

Does it happen again if you try downloading it again? It did for me. If it does, could you post a VOD link here so the devs can duplicate the issue?

**Comment by Endosxn** [comment] 2023-04-01 13:19
I'll try and let you know, should I change the number of threads this time or leave it at 10?

**Comment by Templayer** [comment] 2023-04-01 13:21
> I'll try and let you know, should I change the number of threads this time or leave it at 10?

I would keep it at 10 first and if it does get stuck again, try a third time, but with less threads. Just to see if that makes a difference, I guess.

**Comment by Endosxn** [comment] 2023-04-01 17:42
I 

> > I'll try and let you know, should I change the number of threads this time or leave it at 10?
> 
> I would keep it at 10 first and if it does get stuck again, try a third time, but with less threads. Just to see if that makes a difference, I guess.

I tried, stuck on 99% again, I'll try fewer threads next-time

**Comment by Templayer** [comment] 2023-04-01 18:17
> I
> 
> > > I'll try and let you know, should I change the number of threads this time or leave it at 10?
> > 
> > 
> > I would keep it at 10 first and if it does get stuck again, try a third time, but with less threads. Just to see if that makes a difference, I guess.
> 
> I tried, stuck on 99% again, I'll try fewer threads next-time

And don't forget to post a VOD link so it can be duplicated.

**Comment by Endosxn** [comment] 2023-04-01 18:32
> > I
> > > > I'll try and let you know, should I change the number of threads this time or leave it at 10?
> > > 
> > > 
> > > I would keep it at 10 first and if it does get stuck again, try a third time, but with less threads. Just to see if that makes a difference, I guess.
> > 
> > 
> > I tried, stuck on 99% again, I'll try fewer threads next-time
> 
> And don't forget to post a VOD link so it can be duplicated.

can be duplicated? here's the link - https://www.twitch.tv/videos/1777474493?t=2h1m27s

**Comment by Templayer** [comment] 2023-04-01 19:15
> > > I
> > > > > I'll try and let you know, should I change the number of threads this time or leave it at 10?
> > > > 
> > > > 
> > > > I would keep it at 10 first and if it does get stuck again, try a third time, but with less threads. Just to see if that makes a difference, I guess.
> > > 
> > > 
> > > I tried, stuck on 99% again, I'll try fewer threads next-time
> > 
> > 
> > And don't forget to post a VOD link so it can be duplicated.
> 
> can be duplicated? here's the link - https://www.twitch.tv/videos/1777474493?t=2h1m27s

It got through downloading and it is combining now:

![image](https://user-images.githubusercontent.com/11728067/229309962-4651eeea-95c3-47ad-a580-1b66190ee681.png)

The link you sent contained a timestamp that caused Twitch Downloader to crop out everything until that time in the VOD. Did you mean to do that? Did you download it like that?

**Comment by Endosxn** [comment] 2023-04-01 22:03
> 

Yeah, It was intentional and yes I did download it like that

**Comment by Templayer** [comment] 2023-04-01 22:05
> > 
> 
> Yeah, It was intentional and yes I did download it like that

I tried downloading it like that and without the time cropping. Both times it didn't get stuck. Using 10 threads.

**Comment by Endosxn** [comment] 2023-04-02 00:33
> > > 
> > 
> > 
> > Yeah, It was intentional and yes I did download it like that
> 
> I tried downloading it like that and without the time cropping. Both times it didn't get stuck. Using 10 threads.

That's so odd, what do you think the issue is then? Should I redownload the file? Use a different version? I appreciate you trying yourself, means a lot!

**Comment by Templayer** [comment] 2023-04-02 09:46
> > > > 
> > > 
> > > 
> > > Yeah, It was intentional and yes I did download it like that
> > 
> > 
> > I tried downloading it like that and without the time cropping. Both times it didn't get stuck. Using 10 threads.
> 
> That's so odd, what do you think the issue is then? Should I redownload the file? Use a different version? I appreciate you trying yourself, means a lot!

I'm not a dev for this project, I'm just a user like you. I would try time-cropping it differently (for example a few seconds in time-cropping difference than what you had set up), if that doesn't work and you really want to download it, then try using just one thread and if even that doesn't work, then try using a different computer.

**Comment by Endosxn** [comment] 2023-04-03 00:06
Okay, I'll try using 4 threads and change the timestamp a little

**Comment by Endosxn** [comment] 2023-04-03 10:19
> Okay, I'll try using 4 threads and change the timestamp a little

IT WORKED, I changed the timestamp and the threads and it worked! Not sure which one made the difference but I'm grateful for the help Templayer

**Comment by Templayer** [comment] 2023-04-03 11:33
> > Okay, I'll try using 4 threads and change the timestamp a little
> 
> IT WORKED, I changed the timestamp and the threads and it worked! Not sure which one made the difference but I'm grateful for the help Templayer

I would be happier if this annoying bug finally got squashed. :(

**Comment by ScrubN** [comment] 2023-04-03 15:25
> > > Okay, I'll try using 4 threads and change the timestamp a little
> > 
> > IT WORKED, I changed the timestamp and the threads and it worked! Not sure which one made the difference but I'm grateful for the help Templayer
> 
> I would be happier if this annoying bug finally got squashed. :(

I would too. My guess is that the final few threads get deadlocked, but I simply do not know what causes the deadlock. As far as I can tell the issue seems to disappear between runs rather than through a difference in configuration. In addition, there is a timeout configured on the actual data downloader, so the issue is not network-related.

**Comment by Templayer** [comment] 2023-04-03 19:05
> > And I forgot about the threads entirely. By the way, they are somewhat hard to see with bigger fonts (maybe their input field could react to their size instead of being hardcoded? And that's on a 2K screen. If I had a 4k screen then that number might be completely invisible :P ):
> 
> I will remove the hard coded width. I think I will also be removing download threads from the interface, instead making it an internal calculation. With 720p VODs even 1 thread is able to saturate over 40MB/s (~1/3 gigabit) due to HttpClient being less limited than WebClient. Threads are only needed now for low resolution VODs where downloading the video file contents becomes a smaller portion of the time spent.

Just move it to the settings and make the 0 value the default, with the GUI showing it as "Dynamic", which is what you are proposing (a dynamic thread count based on size and quality). Don't remove options, some people might find it useful (maybe even as workarounds around glitches ;) ). You could create an "Advanced" tab for the settings to put this into. :)

Don't know how the others, but I really dislike the removal of settings and options. That's what Microsoft does... yuck. (one of many reasons why I don't (or ever will) have Win10/Win11/Win11+)

**Comment by Templayer** [comment] 2023-05-08 17:28
> For me, this happens everytime when trying to download this VOD - https://www.twitch.tv/videos/1727120503

So, I've tried downloading this again (not knowing that the VOD is no longer available) to find out if it still gets stuck.

Instead of telling me that the VOD is no longer available, I got a nullreference in the application.

![image](https://user-images.githubusercontent.com/11728067/236888575-7b025d7e-7f4f-48bb-a297-85c814af0723.png)

![image](https://user-images.githubusercontent.com/11728067/236888797-97407a32-fb4e-4b56-847d-dd62a655d754.png)

(see the window header for the app version)

I would expect it to fail more graciously. Nullpointers/Nullreferences propagated to the user are a sign of bad code design.

Maybe this should be made into an issue?

Also, I cannot find the log files for attachment. Tried the installation folder, then my local system folder for app data "C:\Users\Templayer7\AppData\Local\TwitchDownloaderWPF\"... no dice. Where are the logs stored? I feel like I have already asked this question before...

**Comment by ScrubN** [comment] 2023-07-16 05:33
I have rewritten the video part download system to use a manually managed queue instead of relying on a magic black box function and a semaphore. Hopefully this fixes this issue.

**Closed** 2023-07-23 06:00 UTC
Labels: bug, debugging

**Comment by ScrubN** [comment] 2023-08-30 05:57
> I have rewritten the video part download system to use a manually managed queue instead of relying on a magic black box function and a semaphore. Hopefully this fixes this issue.

A bit late, but it was not fixed by that PR.
I have found the true source of the issue though and it 100% definitely fixes it this time: #792
